const S='worknotice_v3_20261001';
const today=new Date(); const iso=d=>d.toISOString().slice(0,10); const add=n=>{let d=new Date();d.setDate(d.getDate()+n);return iso(d)};
const seed={currentUser:1,users:[{id:1,name:'이희수',team:'미들웨어팀',role:'TP'},{id:2,name:'김DB',team:'DB팀',role:'DB'},{id:3,name:'박WAS',team:'WAS팀',role:'WAS'},{id:4,name:'최WEB',team:'WEB팀',role:'WEB'}],tasks:[{id:101,title:'OOOO시스템 노후서버 교체',purpose:'노후 서버 교체 및 서비스 정상화 확인',content:'관련 담당자는 절차를 확인하고 작업에 참여해주세요.',ownerId:1,participantIds:[1,2,3],departments:['TP','DB','WAS'],status:'scheduled',date:add(1),start:'22:00',end:'23:20',createdAt:new Date().toISOString()},{id:102,title:'OOOO서비스 오픈 모니터링',purpose:'서비스 오픈 후 시스템 상태 및 주요 지표 모니터링',content:'오픈 시간 동안 관련 담당자는 서비스 상태를 확인해주세요.',ownerId:2,participantIds:[1,2],departments:['TP','DB'],status:'draft',date:add(4),start:'23:00',end:'00:30',createdAt:new Date().toISOString()},{id:103,title:'OOOO시스템 고도화 인프라 회의',purpose:'시스템 고도화 관련 인프라 구성 및 작업 일정 협의',content:'관련 인프라 담당자가 참석하여 구성 및 일정을 논의합니다.',ownerId:3,participantIds:[1,3],departments:['TP','WAS'],status:'done',date:add(-2),start:'01:00',end:'01:40',createdAt:new Date().toISOString()},{id:104,title:'OOOO시스템 정기점검 일정 조율',purpose:'시스템 정기점검',content:'가능한 일정에 응답해주세요.',ownerId:2,participantIds:[1,2,4],departments:['DB','WEB'],status:'poll',date:'',start:'',end:'',createdAt:new Date().toISOString()}],steps:[{id:1,taskId:101,order:1,server:'APP01',dept:'TP',desc:'서비스 상태 확인',command:'tmadmin\nsi',start:'22:00',end:'22:10',assigneeId:1,status:'waiting'},{id:2,taskId:101,order:2,server:'DB01',dept:'DB',desc:'DB 백업 상태 확인',command:'backup_check',start:'22:10',end:'22:25',assigneeId:2,status:'waiting'},{id:3,taskId:101,order:3,server:'APP01',dept:'WAS',desc:'WAS 재기동 및 확인',command:'restart_service.sh',start:'22:25',end:'22:45',assigneeId:3,status:'waiting'},{id:4,taskId:103,order:1,server:'WAS01',dept:'WAS',desc:'서비스 재기동',command:'restart.sh',start:'01:00',end:'01:20',assigneeId:3,status:'done'}],notifications:[{id:1,userId:1,type:'작업',title:'새 작업에 참여자로 지정되었습니다.',text:'OOOO시스템 노후서버 교체',read:false},{id:2,userId:1,type:'계정',title:'운영 계정 만료 예정',text:'APP 운영계정 만료일까지 D-7',read:false},{id:3,userId:1,type:'백업',title:'백업 확인 필요',text:'OOOO시스템 정기 백업 결과를 확인해주세요.',read:true}],polls:[{id:1,taskId:104,label:`${add(5)} 22:00`,responses:{1:'가능',2:'가능',4:'미정'}},{id:2,taskId:104,label:`${add(6)} 23:00`,responses:{1:'가능',2:'불가능',4:'가능'}}],logs:[]};
let db=JSON.parse(localStorage.getItem(S)||'null')||seed; let page='dashboard',detailId=null,tab='overview',toastTimer;
function save(){localStorage.setItem(S,JSON.stringify(db))} function user(id){return db.users.find(x=>x.id==id)||{name:'-',role:'-'}} function task(id){return db.tasks.find(x=>x.id==id)}
const statusMap={draft:'작성 중',poll:'일정 조율 중',scheduled:'작업 예정',progress:'진행 중',done:'완료'}; function badge(s){return `<span class="badge ${s}">${statusMap[s]}</span>`}
function toast(t){document.body.insertAdjacentHTML('beforeend',`<div class="toast" id="toast">${t}</div>`);clearTimeout(toastTimer);toastTimer=setTimeout(()=>document.getElementById('toast')?.remove(),1800)}
function log(taskId,text){db.logs.unshift({id:Date.now(),taskId,text,at:new Date().toISOString(),userId:db.currentUser});save()}
function nav(p){page=p;detailId=null;render()} function openTask(id){detailId=id;page='detail';tab='overview';render()}
function layout(body,title){const unread=db.notifications.filter(n=>n.userId==db.currentUser&&!n.read).length;return `<div class="app"><aside class="sidebar"><div class="brand">WorkNotice<small>업무 작업 알림 · 협업 시스템</small></div><div class="nav">${[['dashboard','대시보드'],['calendar','작업 캘린더'],['tasks','전체 작업'],['my','내 작업'],['notifications',`알림 ${unread?`(${unread})`:''}`]].map(([p,n])=>`<button class="${page==p?'active':''}" onclick="nav('${p}')">${n}</button>`).join('')}</div></aside><main class="main"><header class="topbar"><strong>${title}</strong><div class="top-actions"><select onchange="changeUser(this.value)">${db.users.map(u=>`<option value="${u.id}" ${u.id==db.currentUser?'selected':''}>${u.name} / ${u.role}</option>`).join('')}</select><button class="btn" onclick="nav('notifications')">🔔 ${unread||''}</button><button class="btn primary" onclick="newTaskModal()">+ 새 작업</button></div></header><div class="content">${body}</div></main></div>`}
function changeUser(id){db.currentUser=+id;save();render()}
function dashboard(){const mine=db.tasks.filter(t=>t.ownerId==db.currentUser||t.participantIds.includes(db.currentUser));const upcoming=mine.filter(t=>t.status=='scheduled');const todayTasks=mine.filter(t=>t.date==iso(today));const todo=mine.filter(t=>['draft','poll'].includes(t.status));const done=mine.filter(t=>t.status=='done');let body=`<div class="grid4">${[['오늘 작업',todayTasks.length],['예정 작업',upcoming.length],['응답/작성 필요',todo.length],['완료 작업',done.length]].map(x=>`<div class="card stat"><div class="muted">${x[0]}</div><div class="num">${x[1]}</div></div>`).join('')}</div><div class="section-head"><h2>나의 할 일</h2></div><div class="card">${todo.length?todo.map(t=>`<div class="todo"><div><b>${t.title}</b><div class="muted">${t.status=='poll'?'일정 응답이 필요합니다.':'작업 내용 및 절차 확인이 필요합니다.'}</div></div><button class="btn small" onclick="openTask(${t.id})">확인</button></div>`).join(''):'<div class="empty">현재 처리할 항목이 없습니다.</div>'}</div><div class="section-head"><h2>다가오는 작업</h2><button class="btn small" onclick="nav('calendar')">캘린더 보기</button></div>${taskList(upcoming.slice(0,6))}`;return layout(body,'대시보드')}
function taskList(arr){if(!arr.length)return `<div class="card empty">표시할 작업이 없습니다.</div>`;return `<div class="list">${arr.map(t=>`<div class="task-row" onclick="openTask(${t.id})"><div><div class="task-title">${t.title}</div><div class="muted">${t.purpose||''}</div></div><div>${t.date||'일정 미정'}<br><span class="muted">${t.start||''} ${t.end?`~ ${t.end}`:''}</span></div><div>${t.departments.join(' · ')}</div><div>${user(t.ownerId).name}</div><div>${badge(t.status)}</div></div>`).join('')}</div>`}
function tasksPage(mine=false){let arr=db.tasks.filter(t=>!mine||t.ownerId==db.currentUser||t.participantIds.includes(db.currentUser));let body=`<div class="filters"><input id="q" placeholder="작업명, 내용 검색" oninput="filterTasks(${mine})"><select id="sf" onchange="filterTasks(${mine})"><option value="">전체 상태</option>${Object.entries(statusMap).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div id="taskResults">${taskList(arr)}</div>`;return layout(body,mine?'내 작업':'전체 작업')}
function filterTasks(mine){let q=document.getElementById('q').value.toLowerCase(),s=document.getElementById('sf').value;let a=db.tasks.filter(t=>(!mine||t.ownerId==db.currentUser||t.participantIds.includes(db.currentUser))&&(!s||t.status==s)&&(`${t.title} ${t.content} ${t.purpose}`.toLowerCase().includes(q)));document.getElementById('taskResults').innerHTML=taskList(a)}
function calendarPage(){let view=new Date(today.getFullYear(),today.getMonth(),1),y=view.getFullYear(),m=view.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();let cells=[];for(let i=0;i<42;i++){let d=i-first+1,out=false,dt;if(d<1){dt=new Date(y,m-1,prev+d);out=true}else if(d>days){dt=new Date(y,m+1,d-days);out=true}else dt=new Date(y,m,d);let ds=iso(dt),ev=db.tasks.filter(t=>t.date==ds);cells.push(`<div class="day ${out?'out':''}"><div class="date-num">${dt.getDate()}</div>${ev.map(t=>`<div class="event ${t.status}" onclick="openTask(${t.id})">${t.start||''} ${t.title}</div>`).join('')}</div>`)}let body=`<div class="calendar-head"><h2>${y}년 ${m+1}월</h2><div class="muted">작업을 클릭하면 상세 내용을 확인할 수 있습니다.</div></div><div class="calendar-scroll"><div class="calendar">${['일','월','화','수','목','금','토'].map(x=>`<div class="dow">${x}</div>`).join('')}${cells.join('')}</div></div>`;return layout(body,'작업 캘린더')}
function notificationsPage(){let ns=db.notifications.filter(n=>n.userId==db.currentUser);let body=`<div class="card"><div class="section-head" style="margin-top:0"><h2>알림센터</h2><button class="btn small" onclick="readAll()">모두 읽음</button></div>${ns.length?ns.map(n=>`<div class="notification"><div class="dot ${n.read?'read':''}"></div><div><b>${n.title}</b><div class="muted">${n.text}</div><span class="badge">${n.type}</span></div><button class="btn small" onclick="toggleRead(${n.id})">${n.read?'읽음':'확인'}</button></div>`).join(''):'<div class="empty">알림이 없습니다.</div>'}</div>`;return layout(body,'알림')}
function readAll(){db.notifications.filter(n=>n.userId==db.currentUser).forEach(n=>n.read=true);save();render()} function toggleRead(id){let n=db.notifications.find(x=>x.id==id);n.read=!n.read;save();render()}
function detail(){let t=task(detailId);if(!t)return tasksPage();let steps=db.steps.filter(s=>s.taskId==t.id).sort((a,b)=>a.order-b.order);let body=`<div class="detail-head"><div><h1>${t.title}</h1><div class="meta">${badge(t.status)}<span>📅 ${t.date||'일정 미정'} ${t.start||''}</span><span>👤 ${user(t.ownerId).name}</span><span>${t.departments.join(' · ')}</span></div></div><div><button class="btn" onclick="editTaskModal(${t.id})">수정</button> ${t.status=='scheduled'?`<button class="btn primary" onclick="startTask(${t.id})">작업 시작</button>`:''}</div></div><div class="tabs">${[['overview','개요'],['procedure','공동 절차서'],['schedule','일정 조율'],['activity','활동 기록']].map(([k,v])=>`<button class="${tab==k?'active':''}" onclick="setTab('${k}')">${v}</button>`).join('')}</div>${tabContent(t,steps)}`;return layout(body,'작업 상세')}
function setTab(t){tab=t;render()}
function tabContent(t,steps){if(tab=='overview')return `<div class="grid4"><div class="card"><b>작업 목적</b><p>${t.purpose||'-'}</p></div><div class="card"><b>작업 일정</b><p>${t.date||'미정'}<br>${t.start||''} ${t.end?`~ ${t.end}`:''}</p></div><div class="card"><b>주도 담당자</b><p>${user(t.ownerId).name}</p></div><div class="card"><b>참여자</b><p>${t.participantIds.map(x=>user(x).name).join(', ')}</p></div></div><div class="section-head"><h2>공지 내용</h2></div><div class="card">${t.content||'등록된 내용이 없습니다.'}</div>`;
if(tab=='procedure')return `<div class="section-head" style="margin-top:0"><div><h2>공동 작업 절차서</h2><span class="muted">메일 첨부 엑셀 대신 모든 담당자가 같은 표를 수정합니다.</span></div><button class="btn primary" onclick="addStepModal(${t.id})">+ 단계 추가</button></div><div class="table-wrap"><table class="procedure"><thead><tr><th>No.</th><th>대상 서버</th><th>업무</th><th>작업 내용 / 명령어</th><th>시작</th><th>종료</th><th>담당자</th><th>상태</th><th></th></tr></thead><tbody>${steps.map(s=>`<tr><td>${s.order}</td><td>${s.server}</td><td>${s.dept}</td><td><b>${s.desc}</b><div class="code">${s.command||'-'}</div></td><td>${s.start}</td><td>${s.end}</td><td>${user(s.assigneeId).name}</td><td>${s.status=='done'?'완료':s.status=='progress'?'진행 중':'대기'}</td><td><button class="btn small" onclick="editStepModal(${s.id})">수정</button></td></tr>`).join('')||`<tr><td colspan="9" class="empty">아직 작성된 작업 단계가 없습니다.</td></tr>`}</tbody></table></div>`;
if(tab=='schedule'){let polls=db.polls.filter(p=>p.taskId==t.id);return `<div class="section-head" style="margin-top:0"><div><h2>일정 조율</h2><span class="muted">메일 회신 대신 후보 일정에 바로 응답합니다.</span></div><button class="btn" onclick="addPoll(${t.id})">+ 후보 일정</button></div><div class="card">${polls.length?polls.map(p=>`<div class="notice"><b>${p.label}</b><div style="margin-top:10px">${t.participantIds.map(uid=>`<span style="display:inline-block;margin-right:12px">${user(uid).name}: <select onchange="pollResponse(${p.id},${uid},this.value)"><option>미정</option><option ${p.responses[uid]=='가능'?'selected':''}>가능</option><option ${p.responses[uid]=='불가능'?'selected':''}>불가능</option></select></span>`).join('')}</div><div style="margin-top:10px">${t.participantIds.every(uid=>p.responses[uid]=='가능')?`<button class="btn primary" onclick="confirmPoll(${p.id})">이 일정으로 확정</button> <span class="badge progress">모두 가능</span>`:''}</div></div>`).join(''):'<div class="empty">등록된 후보 일정이 없습니다.</div>'}</div>`}
let logs=db.logs.filter(l=>l.taskId==t.id);return `<div class="card">${logs.length?logs.map(l=>`<div class="notification"><div class="dot read"></div><div><b>${l.text}</b><div class="muted">${new Date(l.at).toLocaleString('ko-KR')} · ${user(l.userId).name}</div></div></div>`).join(''):'<div class="empty">아직 활동 기록이 없습니다.</div>'}</div>`}
function newTaskModal(){taskModal()} function editTaskModal(id){taskModal(task(id))}
function taskModal(t={}){modal(`<h2>${t.id?'작업 수정':'새 작업 등록'}</h2><p class="muted">전자우편을 작성하듯 대상자, 제목, 일정과 내용을 입력하세요.</p><div class="form-grid"><div class="field full"><label>받는 사람 / 참여자</label><div>${db.users.map(u=>`<label style="margin-right:12px"><input type="checkbox" name="parts" value="${u.id}" ${(t.participantIds||[db.currentUser]).includes(u.id)?'checked':''}> ${u.name} (${u.role})</label>`).join('')}</div></div><div class="field full"><label>작업 제목</label><input id="mtitle" value="${t.title||''}" placeholder="예: OOOO시스템 노후서버 교체"></div><div class="field"><label>주도 담당자</label><select id="mowner">${db.users.map(u=>`<option value="${u.id}" ${u.id==(t.ownerId||db.currentUser)?'selected':''}>${u.name} / ${u.role}</option>`).join('')}</select></div><div class="field"><label>관련 업무 (쉼표 구분)</label><input id="mdept" value="${(t.departments||[]).join(', ')}" placeholder="TP, DB, WAS"></div><div class="field"><label>작업 날짜</label><input type="date" id="mdate" value="${t.date||''}"></div><div class="field"><label>시간</label><div><input type="time" id="mstart" value="${t.start||''}"> ~ <input type="time" id="mend" value="${t.end||''}"></div></div><div class="field full"><label>작업 목적</label><input id="mpurpose" value="${t.purpose||''}"></div><div class="field full"><label>공지 내용</label><textarea id="mcontent" rows="6" placeholder="관련 담당자에게 공유할 내용을 작성하세요.">${t.content||''}</textarea></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">취소</button><button class="btn primary" onclick="saveTask(${t.id||0})">${t.id?'저장':'작업 등록 및 공유'}</button></div>`)}
function saveTask(id){let title=document.getElementById('mtitle').value.trim();if(!title)return toast('작업 제목을 입력해주세요.');let parts=[...document.querySelectorAll('input[name=parts]:checked')].map(x=>+x.value),date=document.getElementById('mdate').value;let obj={title,purpose:mpurpose.value,content:mcontent.value,ownerId:+mowner.value,participantIds:parts,departments:mdept.value.split(',').map(x=>x.trim()).filter(Boolean),date,start:mstart.value,end:mend.value,status:date?'scheduled':'draft'};if(id){Object.assign(task(id),obj);log(id,'작업 정보를 수정했습니다.')}else{obj.id=Date.now();obj.createdAt=new Date().toISOString();db.tasks.unshift(obj);parts.filter(x=>x!=db.currentUser).forEach(uid=>db.notifications.unshift({id:Date.now()+uid,userId:uid,type:'작업',title:'새 작업에 참여자로 지정되었습니다.',text:title,read:false}));log(obj.id,'새 작업을 등록했습니다.');detailId=obj.id;page='detail'}save();closeModal();render();toast(id?'작업이 수정되었습니다.':'작업이 등록되었습니다.')}
function addStepModal(taskId){stepModal({taskId,order:db.steps.filter(x=>x.taskId==taskId).length+1})} function editStepModal(id){stepModal(db.steps.find(x=>x.id==id))}
function stepModal(s){modal(`<h2>${s.id?'작업 단계 수정':'작업 단계 추가'}</h2><div class="form-grid"><div class="field"><label>대상 서버</label><input id="sserver" value="${s.server||''}"></div><div class="field"><label>업무</label><input id="sdept" value="${s.dept||''}" placeholder="TP / DB / WAS"></div><div class="field full"><label>작업 내용</label><input id="sdesc" value="${s.desc||''}"></div><div class="field full"><label>명령어</label><textarea id="scmd" rows="4">${s.command||''}</textarea></div><div class="field"><label>시작 시간</label><input type="time" id="sstart" value="${s.start||''}"></div><div class="field"><label>종료 시간</label><input type="time" id="send" value="${s.end||''}"></div><div class="field"><label>담당자</label><select id="sassignee">${db.users.map(u=>`<option value="${u.id}" ${u.id==(s.assigneeId||db.currentUser)?'selected':''}>${u.name}</option>`).join('')}</select></div></div><div class="modal-actions">${s.id?`<button class="btn danger" onclick="deleteStep(${s.id})">삭제</button>`:''}<button class="btn" onclick="closeModal()">취소</button><button class="btn primary" onclick="saveStep(${s.id||0},${s.taskId})">저장</button></div>`)}
function saveStep(id,taskId){let o={taskId,server:sserver.value,dept:sdept.value,desc:sdesc.value,command:scmd.value,start:sstart.value,end:send.value,assigneeId:+sassignee.value};if(id){Object.assign(db.steps.find(x=>x.id==id),o);log(taskId,'작업 절차를 수정했습니다.')}else{o.id=Date.now();o.order=db.steps.filter(x=>x.taskId==taskId).length+1;o.status='waiting';db.steps.push(o);log(taskId,'작업 절차를 추가했습니다.')}save();closeModal();render();toast('작업 절차가 저장되었습니다.')}
function deleteStep(id){let s=db.steps.find(x=>x.id==id);db.steps=db.steps.filter(x=>x.id!=id);db.steps.filter(x=>x.taskId==s.taskId).sort((a,b)=>a.order-b.order).forEach((x,i)=>x.order=i+1);log(s.taskId,'작업 절차를 삭제했습니다.');save();closeModal();render()}
function addPoll(taskId){let label=prompt('후보 일정을 입력하세요. 예: 2026-10-12 22:00');if(!label)return;db.polls.push({id:Date.now(),taskId,label,responses:{}});let t=task(taskId);t.status='poll';log(taskId,'일정 후보를 추가했습니다.');save();render()}
function pollResponse(pid,uid,v){let p=db.polls.find(x=>x.id==pid);p.responses[uid]=v;save();render()}
function confirmPoll(pid){let p=db.polls.find(x=>x.id==pid),t=task(p.taskId),m=p.label.match(/(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})/);if(m){t.date=m[1];t.start=m[2]}t.status='scheduled';log(t.id,`작업 일정을 ${p.label}(으)로 확정했습니다.`);save();render();toast('일정이 확정되었습니다.')}
function startTask(id){let t=task(id);t.status='progress';log(id,'작업을 시작했습니다.');save();render();toast('작업이 시작되었습니다.')}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="modal"><div class="modal">${html}</div></div>`)} function closeModal(){document.getElementById('modal')?.remove()}
function render(){let html=page=='dashboard'?dashboard():page=='calendar'?calendarPage():page=='tasks'?tasksPage(false):page=='my'?tasksPage(true):page=='notifications'?notificationsPage():detail();document.getElementById('app').innerHTML=html} render();
